- name: Demonstrates the use of list and navigating/accessing list elements
  hosts: ubuntu
  vars:
    software_tools:
      - vim
      - tree
      - net-tools
      - iputils-ping
  tasks:
    - name: Install software tools
      apt: name="{{software_tools}}" state=latest update_cache=yes
